#!/usr/bin/env python3
"""
Fix lifestyle images for wall art listings DP1007–DP1037.

The current lifestyle_room_A/B.jpg files were generated by redo_lifestyle_rooms.py,
which uses DALL-E to create FULL AI scenes with fake art described in the prompt.
This violates the real-product rule — listings must show the ACTUAL product file.

This script:
  1. Uses composite_smart() on the existing bg_lifestyle_room_A/B.jpg bare-wall
     backgrounds (from the older lifestyle_composite_upload.py workflow)
  2. Composites the real product JPG file onto the bare wall
  3. Saves the result as lifestyle_room_A.jpg / lifestyle_room_B.jpg (overwriting)
  4. Uploads to the correct Etsy listing at the correct ranks

Usage:
  python tools/batch_fix_wall_art_lifestyle.py --preview          # generate only
  python tools/batch_fix_wall_art_lifestyle.py                    # generate + upload
  python tools/batch_fix_wall_art_lifestyle.py --pids DP1007 DP1012  # specific PIDs
"""

import os, sys, json, urllib.request, time, argparse
sys.path.insert(0, '/home/user/Etsy')
with open('/home/user/Etsy/.env') as f:
    for line in f:
        line = line.strip()
        if line and not line.startswith('#') and '=' in line:
            k, v = line.split('=', 1)
            os.environ.setdefault(k.strip(), v.strip())

from tools.lifestyle_composite import composite_smart, qc_check
from tools.etsy_api import EtsyAPIClient, EtsyAPIError

ART_DIR = '/home/user/Etsy/data/digital_products/product_files'

# ── Listing ID + rank mapping (from redo_lifestyle_rooms.py, verified) ───────
LISTINGS = {
    'DP1007': {'listing_id': '4509218152', 'ranks': (6, 7)},
    'DP1012': {'listing_id': '4509258172', 'ranks': (6, 7)},
    'DP1013': {'listing_id': '4509258700', 'ranks': (6, 7)},
    'DP1014': {'listing_id': '4509213345', 'ranks': (6, 7)},
    'DP1015': {'listing_id': '4509213533', 'ranks': (6, 7)},
    'DP1016': {'listing_id': '4509213667', 'ranks': (6, 7)},
    'DP1017': {'listing_id': '4509259354', 'ranks': (6, 7)},
    'DP1018': {'listing_id': '4509218860', 'ranks': (6, 7)},
    'DP1019': {'listing_id': '4509214051', 'ranks': (6, 7)},
    'DP1020': {'listing_id': '4509214237', 'ranks': (6, 7)},
    'DP1021': {'listing_id': '4509214477', 'ranks': (6, 7)},
    'DP1022': {'listing_id': '4509219594', 'ranks': (6, 7)},
    'DP1023': {'listing_id': '4509214803', 'ranks': (6, 7)},
    'DP1024': {'listing_id': '4509219904', 'ranks': (6, 7)},
    'DP1025': {'listing_id': '4509215145', 'ranks': (6, 7)},
    'DP1030': {'listing_id': '4509598660', 'ranks': (1, 2)},
    'DP1031': {'listing_id': '4509598784', 'ranks': (1, 2)},
    'DP1032': {'listing_id': '4509593487', 'ranks': (1, 2)},
    'DP1033': {'listing_id': '4509593623', 'ranks': (1, 2)},
    'DP1034': {'listing_id': '4509593697', 'ranks': (1, 2)},
    'DP1035': {'listing_id': '4509600086', 'ranks': (1, 2)},
    'DP1036': {'listing_id': '4509596017', 'ranks': (1, 2)},
    'DP1037': {'listing_id': '4509597559', 'ranks': (1, 2)},
}

# ── Frame colors per product (warm natural wood default; special cases below) ─
# Chosen to match the frame material described in each listing's scene prompts
FRAME_COLORS = {
    'DP1007': (100,  80,  55),   # dark walnut
    'DP1012': ( 55,  55,  55),   # matte black
    'DP1013': (160, 135, 100),   # light ash wood
    'DP1014': (139, 110,  80),   # natural wood
    'DP1015': (175, 148,  75),   # brushed gold
    'DP1016': (160, 140, 110),   # pale natural wood
    'DP1017': (100,  80,  55),   # natural walnut
    'DP1018': (160, 140, 110),   # light oak
    'DP1019': (100,  80,  55),   # natural walnut
    'DP1020': (160, 135, 100),   # pale natural wood
    'DP1021': ( 80,  60,  40),   # dark walnut
    'DP1022': (175, 175, 182),   # brushed silver
    'DP1023': ( 55,  55,  55),   # matte black
    'DP1024': ( 55,  55,  55),   # matte black
    'DP1025': ( 80,  60,  40),   # dark walnut
    'DP1030': (175, 145,  75),   # brushed brass
    'DP1031': (100,  80,  55),   # natural walnut
    'DP1032': ( 80,  55,  40),   # dark mahogany
    'DP1033': ( 55,  55,  55),   # matte black
    'DP1034': (139, 110,  80),   # natural wood
    'DP1035': (155, 125,  85),   # natural bamboo/rattan
    'DP1036': ( 55,  55,  55),   # matte black
    'DP1037': (100,  90,  60),   # olive wood
}

ALL_PIDS = list(LISTINGS.keys())


def get_auth_headers(client):
    return {
        "Authorization": f"Bearer {client.access_token}",
        "x-api-key": f"{client.client_id}:{client.client_secret}",
    }


def get_image_ranks(listing_id, headers):
    url = f"https://openapi.etsy.com/v3/application/listings/{listing_id}/images"
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            imgs = json.loads(resp.read()).get('results', [])
            return {img['rank']: img['listing_image_id'] for img in imgs}
    except Exception as e:
        print(f"    Could not get images: {e}")
        return {}


def upload_image(client, listing_id, img_path, rank):
    headers = get_auth_headers(client)
    shop_id = client.shop_id

    existing = get_image_ranks(listing_id, headers)
    if rank in existing:
        url_del = (f"https://openapi.etsy.com/v3/application/shops/{shop_id}"
                   f"/listings/{listing_id}/images/{existing[rank]}")
        try:
            urllib.request.urlopen(
                urllib.request.Request(url_del, headers=headers, method="DELETE"),
                timeout=15)
            print(f"    Deleted old rank={rank} image")
            time.sleep(0.5)
        except Exception as e:
            print(f"    Could not delete: {e}")

    for attempt in range(3):
        try:
            client.upload_listing_image(listing_id, img_path, rank=rank)
            print(f"    Uploaded rank={rank}: {os.path.basename(img_path)}")
            return True
        except EtsyAPIError as e:
            if e.status == 401:
                client.refresh_access_token()
            elif e.status == 429:
                time.sleep(15)
            elif e.status == 500 and attempt < 2:
                time.sleep(5)
            else:
                print(f"    Upload failed: {e}")
                return False
    return False


def composite_one(pid, scene_letter, bg_suffix):
    """
    Composite real product art onto bare-wall background.
    Returns ('ok'|'skip'|'fail', out_path)
    """
    out_dir  = os.path.join(ART_DIR, f'{pid}_listing_images')
    art_path = os.path.join(ART_DIR, f'{pid}.jpg')
    bg_path  = os.path.join(out_dir, f'bg_lifestyle_room_{bg_suffix}.jpg')
    out_path = os.path.join(out_dir, f'lifestyle_room_{scene_letter}.jpg')

    if not os.path.exists(art_path):
        print(f"    SKIP: art file missing — {art_path}")
        return 'skip', out_path
    if not os.path.exists(bg_path):
        print(f"    SKIP: background missing — {bg_path}")
        return 'skip', out_path

    frame_color = FRAME_COLORS.get(pid, (139, 110, 80))

    ok, furniture_y, frame_bottom = composite_smart(
        bg_path, art_path, out_path,
        frame_color=frame_color,
        art_pct=0.25,
        min_clearance=60,
    )

    if not ok:
        print(f"    Composite failed")
        return 'fail', out_path

    print(f"    Composited: furniture_y={furniture_y}  frame_bottom={frame_bottom}")

    pass_qc, reason = qc_check(out_path, 0, frame_bottom, clearance_min=40)
    if not pass_qc:
        print(f"    QC note: {reason}")

    return 'ok', out_path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--preview', action='store_true',
                        help='Composite only — do not upload')
    parser.add_argument('--pids', nargs='+', default=None,
                        help='Only process these PIDs (e.g. --pids DP1007 DP1012)')
    args = parser.parse_args()

    client = None
    if not args.preview:
        client = EtsyAPIClient()
        client.refresh_access_token()

    pids = args.pids if args.pids else ALL_PIDS

    results = []
    for pid in pids:
        info = LISTINGS.get(pid)
        if not info:
            print(f"\nSkipping {pid} — not in LISTINGS dict")
            continue

        rank_a, rank_b = info['ranks']
        listing_id = int(info['listing_id'])

        print(f"\n{'='*60}")
        print(f"  {pid}  →  listing={listing_id}  ranks={rank_a},{rank_b}")
        print(f"{'='*60}")

        # ── Scene A ────────────────────────────────────────────────────────
        print(f"  Scene A (rank={rank_a}):")
        status_a, path_a = composite_one(pid, 'A', 'A')

        if status_a == 'ok' and not args.preview:
            ok = upload_image(client, listing_id, path_a, rank_a)
            status_a = 'uploaded' if ok else 'upload_failed'
            time.sleep(1)

        # ── Scene B ────────────────────────────────────────────────────────
        print(f"  Scene B (rank={rank_b}):")
        status_b, path_b = composite_one(pid, 'B', 'B')

        if status_b == 'ok' and not args.preview:
            ok = upload_image(client, listing_id, path_b, rank_b)
            status_b = 'uploaded' if ok else 'upload_failed'
            time.sleep(1)

        results.append((pid, status_a, status_b))

    print(f"\n{'='*60}")
    print("BATCH COMPLETE")
    print(f"{'='*60}")
    for pid, sa, sb in results:
        def icon(s):
            return '✓' if s in ('ok', 'uploaded') else '⚠' if s == 'skip' else '✗'
        print(f"  {icon(sa)} {pid}-A: {sa}   {icon(sb)} {pid}-B: {sb}")

    print("\nNOTE: DP1025 bg_lifestyle_room_A/B may be a full scene (std>55).")
    print("Inspect DP1025 results and regenerate background if composite looks wrong.")


if __name__ == '__main__':
    main()
