#!/usr/bin/env python3
"""
upload_flat_previews.py
Upload center-crop flat art preview photos to listings that are failing the
art_in_photos integrity check (no clean product photo in listing photos).

Flat previews are generated by tools/generate_flat_preview.py and live in:
  data/digital_products/flat_previews/DP####_flat_preview.jpg

The photo is inserted at rank=3 (after hero lifestyle and what's-included shots)
to preserve the existing photo sequence. Etsy renumbers higher-ranked photos up.

Usage:
    python tools/upload_flat_previews.py --preview   # dry run
    python tools/upload_flat_previews.py             # upload all missing
    python tools/upload_flat_previews.py --dp DP1012,DP1030  # specific DPs
"""

import argparse
import sys
import time
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
sys.path.insert(0, str(BASE_DIR))
from tools.etsy_api import EtsyAPIClient

FLAT_PREVIEW_DIR = BASE_DIR / "data" / "digital_products" / "flat_previews"

# Listings confirmed to be missing a flat art preview photo
# (failing art_in_photos check; all have correct upscaled source files)
TARGETS = {
    "DP1012": 4509258172,
    "DP1030": 4509598660,
    "DP1031": 4509598784,
    "DP1032": 4509593487,
    "DP1036": 4509596017,
    "DP1037": 4509597559,
}

# Insert flat preview at rank 3 (after hero + what's-included)
PHOTO_RANK = 3

INTER_CALL_DELAY = 1.0  # seconds between uploads (image uploads are heavier than PATCH)


def get_photo_count(api, lid: int) -> int:
    try:
        images = api.get_listing_images(lid)
        return len(images)
    except Exception:
        return -1


def upload_preview(api, dp_id: str, lid: int, preview_path: Path, preview: bool) -> str:
    if preview:
        size_kb = preview_path.stat().st_size // 1024
        return f"preview — would upload {preview_path.name} ({size_kb} KB) at rank={PHOTO_RANK}"
    try:
        api.upload_listing_image(lid, str(preview_path), rank=PHOTO_RANK)
        return "ok"
    except Exception as e:
        err = str(e)
        if "429" in err:
            return "rate_limited"
        return f"error: {err[:100]}"


def main():
    parser = argparse.ArgumentParser(description="Upload flat art preview photos to listings")
    parser.add_argument("--preview", action="store_true", help="Dry run — no uploads")
    parser.add_argument("--dp", type=str, help="Comma-separated DP codes, e.g. DP1012,DP1030")
    args = parser.parse_args()

    if args.dp:
        dp_filter = {d.strip().upper() for d in args.dp.split(",")}
        targets = {dp: lid for dp, lid in TARGETS.items() if dp in dp_filter}
    else:
        targets = TARGETS

    # Check that preview files exist before starting
    missing_files = []
    for dp_id in targets:
        p = FLAT_PREVIEW_DIR / f"{dp_id}_flat_preview.jpg"
        if not p.exists():
            missing_files.append(dp_id)
    if missing_files:
        print(f"ERROR: flat preview files not found for: {', '.join(missing_files)}")
        print(f"Run first: python tools/generate_flat_preview.py")
        sys.exit(1)

    api = EtsyAPIClient()

    ok = 0
    rate_limited = 0
    errors = []

    print(f"\n{'PREVIEW' if args.preview else 'APPLY'} — uploading flat previews to {len(targets)} listings\n")

    for i, (dp_id, lid) in enumerate(sorted(targets.items()), 1):
        preview_path = FLAT_PREVIEW_DIR / f"{dp_id}_flat_preview.jpg"

        # Show current photo count for context
        if not args.preview:
            n_photos = get_photo_count(api, lid)
            photo_info = f"{n_photos} photos currently" if n_photos >= 0 else "photo count unknown"
        else:
            photo_info = "dry run"

        print(f"  [{i}/{len(targets)}] {dp_id} → listing {lid}  ({photo_info})")

        status = upload_preview(api, dp_id, lid, preview_path, args.preview)

        if status == "ok":
            print(f"    ✓ uploaded at rank={PHOTO_RANK}")
            ok += 1
        elif status.startswith("preview"):
            print(f"    — {status}")
            ok += 1
        elif status == "rate_limited":
            print(f"    ✗ rate limited — stopping")
            rate_limited += 1
            break
        else:
            print(f"    ✗ {status}")
            errors.append((dp_id, lid, status))

        if not args.preview:
            time.sleep(INTER_CALL_DELAY)

    print(f"\n{'=' * 55}")
    if args.preview:
        print(f"Preview complete: {ok} uploads queued")
    else:
        print(f"Done: {ok} uploaded, {rate_limited} rate-limited, {len(errors)} errors")
    if errors:
        print("Errors:")
        for dp_id, lid, err in errors:
            print(f"  {dp_id} ({lid}): {err}")
    if rate_limited:
        print("Rate limit hit — re-run after the 24h window resets (~02:54 AM tomorrow)")
    if ok and not args.preview:
        print()
        print("Next step: re-run listing_integrity_check.py to confirm art_in_photos passes")
        print("  python tools/listing_integrity_check.py --full --listings",
              ",".join(str(lid) for _, lid in sorted(targets.items())))
    print("=" * 55)


if __name__ == "__main__":
    main()
