#!/usr/bin/env python3
"""Build openscad_models/PRINT_INDEX.md -- one browsable list of every printable file.

    python3 tools/print_index.py            # rewrite the index
    python3 tools/print_index.py --check    # fail if the index is out of date

Written 2026-09-17, when Scott asked for "the updated 3mf and stl files so I can
choose any of them to print" and the honest answer turned out to need a sweep: the
exports live in one flat directory plus five subdirectories merged in from separate
branches, 147 files, and nothing said which of them actually fit a P1S. One of them
did not, and had not for weeks.

Every number here is measured from the file itself, never from the .scad or from a
note written when it was built -- the point of an index Scott prints from is that it
cannot drift away from the mesh it describes.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import mesh_gate

ROOT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                    "openscad_models")
INDEX = os.path.join(ROOT, "PRINT_INDEX.md")

# A check that stops the print from happening at all, as opposed to a note about
# mesh style. Only these mark a file unprintable.
_BLOCKING = ("fits_build_volume", "no_holes", "winding_consistent", "positive_volume")


def _measure(path):
    rel = os.path.relpath(path, ROOT)
    row = {"file": rel, "mb": os.path.getsize(path) / 1e6}
    try:
        checks = {c["check"]: c for c in mesh_gate.gate(path)["checks"]}
    except Exception as exc:
        row["blocking"] = ["unreadable: %s" % exc]
        return row
    ext = mesh_gate._load(path).extents
    row["bbox"] = tuple(float(v) for v in ext)
    row["cm3"] = float(checks["positive_volume"]["detail"].split()[0])
    row["parts"] = int(checks["component_count"]["detail"].split()[0])
    row["blocking"] = [k for k in _BLOCKING if not checks[k]["pass"]]
    notes = []
    if not checks["no_degenerate_faces"]["pass"]:
        notes.append(checks["no_degenerate_faces"]["detail"].split(" zero")[0]
                     + " zero-area faces (harmless; slices clean)")
    if "more than two" in checks["manifold_edges"]["detail"]:
        notes.append("flush-contact edges, repaired by the slicer on import")
    row["notes"] = notes
    return row


def collect():
    rows = []
    for dirpath, _, files in os.walk(ROOT):
        for f in sorted(files):
            if f.lower().endswith((".stl", ".3mf")):
                rows.append(_measure(os.path.join(dirpath, f)))
    rows.sort(key=lambda r: r["file"].lower())
    return rows


def render(rows):
    ok = [r for r in rows if not r["blocking"]]
    bad = [r for r in rows if r["blocking"]]
    out = [
        "# Printable files",
        "",
        "Generated by `python3 tools/print_index.py` -- every figure measured from "
        "the mesh itself, not from its source or its notes.",
        "",
        "**%d files, %d ready to print, %d blocked.** Bambu Lab P1S, 256 x 256 x 256 mm."
        % (len(rows), len(ok), len(bad)),
        "",
    ]
    if bad:
        out += ["## Blocked -- do not print these", "",
                "| file | size mm | why |", "|---|---|---|"]
        for r in bad:
            bb = ("%.1f x %.1f x %.1f" % r["bbox"]) if "bbox" in r else "-"
            out.append("| `%s` | %s | %s |" % (r["file"], bb, ", ".join(r["blocking"])))
        out.append("")
    out += ["## Ready to print", "",
            "| file | size mm | volume | parts | notes |", "|---|---|---|---|---|"]
    for r in ok:
        out.append("| `%s` | %.1f x %.1f x %.1f | %.1f cm3 | %d | %s |"
                   % (r["file"], r["bbox"][0], r["bbox"][1], r["bbox"][2],
                      r["cm3"], r["parts"], "; ".join(r["notes"]) or ""))
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed index no longer matches the files")
    a = ap.parse_args()
    text = render(collect())
    if a.check:
        current = open(INDEX, encoding="utf-8").read() if os.path.exists(INDEX) else ""
        if current != text:
            print("PRINT_INDEX.md is out of date -- run tools/print_index.py")
            return 1
        print("PRINT_INDEX.md matches the files on disk")
        return 0
    with open(INDEX, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote %s" % INDEX)
    return 0


if __name__ == "__main__":
    sys.exit(main())
